pipeline:
  docker:
    image: plugins/docker
    repo: piterjs/piterjs.org
    dockerfile: Dockerfile
    tags: v$$DRONE_BUILD_NUMBER
    secrets: [ docker_username, docker_password ]
  telegram:
    image: appleboy/drone-telegram
    token: $$TELEGRAM_TOKEN
    to: "@mike1pol"
    when:
      status: [ success, failure ]
