pipeline:
  docker:
    image: plugins/docker
    repo: piterjs/piterjs.org
    dockerfile: Dockerfile
    tags: v1.0.0-${DRONE_COMMIT}
    secrets: [ docker_username, docker_password ]
  kube:
    image: vallard/drone-kube
    template: deployment.yaml
    namespace: piterjs-org
    secrets: [ KUBE_TOKEN, KUBE_SERVER ]
