apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piterjs-org
  labels:
    app: piterjs-org
  namespace: piterjs-org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piterjs-org
  template:
    metadata:
      labels:
        app: piterjs-org
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: piterjs-org
        image: piterjs/piterjs.org:v1.0.0-{{build.commit}}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
